### ISSUE TITLE
You use unoptimized wasm build

### ISSUE THREAD

**Issue by MaxGraey** [GuildOfWeavers/galois#11]
You could add `-O3` flag [here](https://github.com/GuildOfWeavers/galois/blob/master/gulpfile.js#L26).

**Comment by bobbinth** [comment]
Good catch! I've enabled optimization in the latest release - but can't say that the difference is really noticeable.

**Comment by MaxGraey** [comment]
this reduce size slightly (-3 kb or ~15%). And should affect to performance but it's hard to tell how signifiant
