### ISSUE TITLE
How about use __free instead __retain/__release pair?

### ISSUE THREAD

**Issue by MaxGraey** [GuildOfWeavers/galois#12]
Did you try use `__free` instead `__retain`/`__release` in places when you use manual memory management like [here](https://github.com/GuildOfWeavers/galois/blob/master/lib/assembly/prime128.as.ts#L137)?
```ts
if (aRef == resRef) {
  rRef = __alloc(elementCount * VALUE_SIZE,0);
}
...
if (aRef == resRef) {
  __free(rRef);
}
```

**Comment by bobbinth** [comment]
I wasn't sure how to properly do it (the [docs](https://docs.assemblyscript.org/details/runtime) don't mention `__free`, though, I found its description [here](https://github.com/AssemblyScript/assemblyscript/tree/master/std/assembly/rt)) - so, wanted to say on the safer side. But if the above works, I'd rather use it for simplicity.

**Comment by bobbinth** [comment]
I've updated this in the latest commit.

**Comment by MaxGraey** [comment]
Great!
