### ISSUE TITLE
Do these operations run in constant time?

### ISSUE THREAD

**Issue by aunyks** [GuildOfWeavers/galois#13]
I've noticed that TypeScript's `bigint` type is used for a lot of operations throughout the project. The [TypeScript docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html#bigint) say that this wraps [JavaScript's abritrary precision integer type](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt). However, the JS BigInt operations [do not run in constant time](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#Cryptography) and are not ready for use in cryptography applications.  

Does this project happen to use a constant time alternative, or are all of these operations in non-constant time as implied?

**Comment by bobbinth** [comment]
At this point you should assume that all operations are **not constant** time. But to elaborate a bit more:

All operations that rely on native JS BigInt are not constant time. But in WASM-based optimizations we don't have this constraint. At this point, WASM optimizations are available only for 128-bit fields, and even there, they only apply to operations on vectors and matrixes. Within WASM, addition and multiplication are constant time, but exponentiation is not.

**Comment by aunyks** [comment]
Gotcha. Thanks for the help.
